
export const INIT_STATE="INIT_STATE"
export const UPDATE_ITEM_AS_FAVOURITES="UPDATE_ITEM_AS_FAVOURITES"
export const DELETE_FAV_ITEM="DELETE_FAV_ITEM"
export const UPDATE_DISPLAY_LIST="UPDATE_DISPLAY_LIST"
